mqtt:
  enabled: True
  host: MQTT IP #change IP
  user: username #change username
  password: password #change IP

detectors:
  coral:
    type: edgetpu
    device: pci #set based on your TPU

go2rtc:
  streams:
    CAM1:
      - rtsp://username:password@CAM 1 IP:554/cam/realmonitor?channel=1&subtype=0 #change to have camera IP, password, and username
    CAM1_sub:
      - rtsp://username:password@CAM 1 IP:554/cam/realmonitor?channel=1&subtype=1 #change to have camera IP, password, and username
    CAM2:
      - rtsp://username:password@CAM 2 IP:554/cam/realmonitor?channel=1&subtype=0 #change to have camera IP, password, and username
    CAM2_sub:
      - rtsp://username:password@CAM 2 IP:554/cam/realmonitor?channel=1&subtype=1 #change to have camera IP, password, and username

birdseye:
  enabled: True
  mode: continuous

cameras:
  CAM1: #Change Name
    ffmpeg:
      inputs:
        - path: rtsp://{IP}:8554/cam1_sub?mp4 #change name
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://{IP}:8554/Cam1?mp4 #change name
          input_args: preset-rtsp-restream
          roles:
            - record
      hwaccel_args: preset-vaapi #change for HW ACCL type
    detect:
      enabled: True
      width: 704
      height: 480
      fps: 5
    record:
      enabled: True
    snapshots:
      enabled: True
    live:
      stream_name: CAM1 #change name

  Frontyard: #change name
    ffmpeg:
      inputs:
        - path: rtsp://{IP}:8554/front_sub?mp4 #change name
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://{IP}:8554/front?mp4 #change name
          input_args: preset-rtsp-restream
          roles:
            - record
      hwaccel_args: preset-vaapi #change for HW ACCL type
    detect:
      enabled: True
      width: 704
      height: 480
      fps: 5
    record:
      enabled: True
    snapshots:
      enabled: True
    live:
      stream_name: front #change name