Version: '1'

services:  
  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      - /mnt/media/downloads:/downloads
    restart: unless-stopped
    user: 1000:1000
    environment:
      - TZ=America/Chicago
# Sonarr Config
      - UN_SONARR_0_URL=http://sonarr.example.com
      - UN_SONARR_0_API_KEY= #Change with API key found in settings tab of aplication
      - UN_SONARR_0_PATHS_0=/downloads
      - UN_SONARR_0_PROTOCOLS=torrent
      - UN_SONARR_0_TIMEOUT=10s
      - UN_SONARR_0_DELETE_ORIG=false
      - UN_SONARR_0_DELETE_DELAY=5m
      # Radarr Config
      - UN_RADARR_0_URL=http://radarr.example.com
      - UN_RADARR_0_API_KEY= #Change with API key fo- UNd in settings tab of aplication
      - UN_RADARR_0_PATHS_0=/downloads
      - UN_RADARR_0_PROTOCOLS=torrent
      - UN_RADARR_0_TIMEOUT=10s
      - UN_RADARR_0_DELETE_ORIG=false
      - UN_RADARR_0_DELETE_DELAY=5m
      # Readarr Config
      - UN_READARR_0_URL=http://radarr.example.com
      - UN_READARR_0_API_KEY= #Change with API key fo- UNd in settings tab of aplication
      - UN_READARR_0_PATHS_0=/downloads
      - UN_READARR_0_PROTOCOLS=torrent
      - UN_READARR_0_TIMEOUT=10s
      - UN_READARR_0_DELETE_ORIG=false
      - UN_READARR_0_DELETE_DELAY=5m
