Version: '1'

services:
#Gluetun VPN tunnel
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 1080:1080/tcp # Socks-5
      - 8112:8112/tcp # Deluge
    volumes:
      - ./config:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER= #Change for your provider
      - OPENVPN_USER= #username from provider
      - OPENVPN_PASSWORD= #password from provider
      - SERVER_REGIONS=US Houston,US Texas #preferred server location
    restart: unless-stopped

